# Model parameters
img_size: 256
batch_size: 16
epochs: 100
peak_photons: 1000

# Data parameters
data_paths: ["/dist_home/siju/test/ChestX-ray_dataset/"]
test_size: 0.1
val_size: 0.1

# Training parameters
g_lr: 5e-6
d_lr: 2e-6
beta_1: 0.5
lambda_gp: 10.0
edge_weight: 5.0

# Paths
log_dir: "logs"
model_dir: "models"
results_dir: "results"
checkpoint_dir: "training_checkpoints"
